name: Deploy to AWS S3

on:
  push:
    branches:
      - main  # o el branch que uses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node (si tu sitio necesita build)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          npm run build  # si tu proyecto tiene build (React, Vite, etc.)

      - name: Deploy to S3
        uses: aws-actions/s3-sync@v2
        with:
          args: --delete
          bucket: adria-porfolio
          region: eu-north-1
          source-dir: ./  # o ./build según tu proyecto
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
